WOOPPlusCloud2/Controllers/FinancialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WOOPPlusCloud2.Models;
using WOOPPlusCloud2.ActionFilters;
using System.Data.Entity;
using System.Threading.Tasks;

namespace WOOPPlusCloud2.Controllers
{
    [Authorize(Roles = "Admin,Manager")]
    [WhitespaceFilter]
   
    [CompressFilter]
    public class FinancialController : Controller
    {
               
        DateTime today = DateTime.Now;
        DateTime fromDate;
        DateTime toDate;

        //Function to assign dates to all views 
        public FormCollection assignDate(FormCollection formCollection)
        {

            if (String.IsNullOrEmpty(formCollection["fromDate"]) && String.IsNullOrEmpty(formCollection["toDate"]))
            {

                fromDate = new DateTime(today.Year, today.Month, 1);
                toDate = DateTime.Today;
            }
            else
            {
                fromDate = DateTime.Parse(formCollection["fromDate"]).Date;
                toDate = DateTime.Parse(formCollection["toDate"]).Date;
            }
            ViewBag.fromDate = fromDate.ToString("dd-MM-yyyy");
            ViewBag.toDate = toDate.ToString("dd-MM-yyyy");
            return formCollection;
        }

        //function to return revenue list from the database
        #region groupFinancesByString

        private List<FinancialProc_Result> groupFinancesByString(List<FinancialProc_Result> finance)
        {
            List<FinancialProc_Result> list = new List<FinancialProc_Result>();

            List<FinancialProc_Result> groupedFinancials = finance.GroupBy(c => c.INSURANCE).Select(c => c.First()).ToList();
            
            foreach (FinancialProc_Result item in groupedFinancials)
            {
                FinancialProc_Result newItem = new FinancialProc_Result();
                IEnumerable<FinancialProc_Result> x = finance.Where(c => c.INSURANCE == item.INSURANCE);

                newItem.TOTALCOST = x.Sum(c => c.TOTALCOST);
                newItem.Orders = x.Sum(c => c.Orders);
                newItem.INSURANCE = item.INSURANCE;
                newItem.SCHEME = item.SCHEME;
                newItem.item_description = item.item_description;
                newItem.VISITTYPE = item.VISITTYPE;
                newItem.MARGIN = x.Sum(c => c.TOTALSELLINGPRICE) - x.Sum(c => c.TOTALCOST);
                newItem.percentage_margins = newItem.MARGIN != 0 && newItem.TOTALCOST != 0 ? $"{newItem.MARGIN / newItem.TOTALCOST * 100:#,###0}" : $"{0:#,###0}";
                newItem.TOTALSELLINGPRICE = x.Sum(c => c.TOTALSELLINGPRICE);
                newItem.TOTALRETAILPRICE = x.Sum(c => c.TOTALRETAILPRICE);
                newItem.SAVINGS = x.Sum(c => c.SAVINGS);
                newItem.percentage_savings = newItem.SAVINGS != 0 && newItem.TOTALRETAILPRICE != 0
                    ? $"{x.Sum(c => c.SAVINGS) / x.Sum(c => c.TOTALRETAILPRICE) * 100:#,###0}"
                    : $"{0:#,###0}";
                newItem.CENTER = item.CENTER;
                list.Add(newItem);
            }
            return list;
        }
        #endregion
        #region Detailed Report
        //Detailed Revenue Report
        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        
        public ActionResult FinancialDetailed(FormCollection fc)
        {

            if (Request.HttpMethod.ToLower() == "post")
            {
                System.Web.Helpers.AntiForgery.Validate();
            }
            assignDate(fc);
            using (ProcedureModels _entities = new ProcedureModels())
            {

                List<FinancialProc_Result> financials = _entities.FinancialProc(fromDate, toDate).ToList();

                if (!string.IsNullOrEmpty(fc["insuranceDropDown"]))
                {
                    financials = financials.Where(c => c.INSURANCE == fc["insuranceDropDown"]).ToList();

                }
                
                if (!string.IsNullOrEmpty(fc["visitsDropDown"]))
                {
                    financials = financials.Where(c => c.VISITTYPE == fc["visitsDropDown"]).ToList();
                }
                if (!String.IsNullOrEmpty(fc["branchDropDown"]))
                {
                    financials = financials.Where(c => c.CENTER == fc["branchDropDown"]).ToList();
                }

                List<FinancialProc_Result> list = new List<FinancialProc_Result>();
                foreach (FinancialProc_Result item in financials)
                {
                    FinancialProc_Result newItem = new FinancialProc_Result
                    {
                        charge_date = item.charge_date,
                        NAMES = item.NAMES,
                        OPNO = item.OPNO,
                        INVOICE = item.INVOICE,
                        TOTALCOST = item.TOTALCOST,
                        INSURANCE = item.INSURANCE,
                        SCHEME = item.SCHEME,
                        item_description = item.item_description,
                        VISITTYPE = item.VISITTYPE,
                        MARGIN = item.TOTALSELLINGPRICE - item.TOTALCOST,
                        CENTER = item.CENTER
                    };
                    newItem.percentage_margins = newItem.MARGIN != 0 && newItem.TOTALCOST != 0 ? $"{newItem.MARGIN / newItem.TOTALCOST * 100:#,###0}" : $"{0:#,###0}";
                    newItem.TOTALSELLINGPRICE = item.TOTALSELLINGPRICE;
                    newItem.TOTALRETAILPRICE = item.TOTALRETAILPRICE;
                    newItem.SAVINGS = item.SAVINGS;
                    newItem.CENTER = item.CENTER;
                    newItem.percentage_savings = newItem.SAVINGS != 0 && newItem.TOTALRETAILPRICE != 0
                        ? $"{item.SAVINGS / item.TOTALRETAILPRICE * 100:#,###0}"
                        : $"{0:#,###0}";
                    list.Add(newItem);
                }
                return View(list);
            }
        }

        #endregion
        #region insuranceRevenue
        // GET: Insurance Revenue 
        [WhitespaceFilter]
        [CompressFilter]
        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        public ActionResult FinancialReportView(FormCollection fc)
        {
            if (Request.HttpMethod.ToLower() == "post")
            {
                System.Web.Helpers.AntiForgery.Validate();
            }
            using (ProcedureModels _entities = new ProcedureModels()) 
            {
                assignDate(fc);
                List<FinancialProc_Result> financials = _entities.FinancialProc(fromDate, toDate).ToList();
                if (!string.IsNullOrEmpty(fc["insuranceDropDown"]))
                {
                    financials = financials.Where(c => c.INSURANCE == fc["insuranceDropDown"]).ToList();

                }
                if (!String.IsNullOrEmpty(fc["branchDropDown"]))
                {
                    financials = financials.Where(c => c.CENTER == fc["branchDropDown"]).ToList();
                }

                //pass the list to perform grouping tasks
                List<FinancialProc_Result> list = groupFinancesByString(financials);
                IEnumerable<FinancialProc_Result> summary = list.AsEnumerable();
                ViewBag.Cost = $"{summary.Sum(c => c.TOTALCOST):#,###0}";
                ViewBag.Selling = $"{summary.Sum(c => c.TOTALSELLINGPRICE):#,###0}";
                ViewBag.Margin = $"{summary.Sum(c => c.MARGIN):#,###0}";
                return View(list);
            }
               
        }
        #endregion

        //Partial Views to Render the Different Revenue Reports
  
        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        public ActionResult DepartmentRevenue(FormCollection fc)
        {
            if (Request.HttpMethod.ToLower() == "post")
            {
                System.Web.Helpers.AntiForgery.Validate();
            }
            assignDate(fc);
            using (ProcedureModels _entities = new ProcedureModels())
            {
                List<FinancialProc_Result> list = new List<FinancialProc_Result>();
                List<FinancialProc_Result> financials = _entities.FinancialProc(fromDate, toDate).ToList();
                if (!string.IsNullOrEmpty(fc["departmentDropDown"]))
                {
                    financials = financials.Where(c => c.item_description == fc["departmentDropDown"]).ToList();

                }
                if (!String.IsNullOrEmpty(fc["branchDropDown"]))
                {
                    financials = financials.Where(c => c.CENTER == fc["branchDropDown"]).ToList();
                }
                List<FinancialProc_Result> groupedFinancials = financials.GroupBy(c => c.item_description).Select(c => c.First()).ToList();
                foreach (FinancialProc_Result item in groupedFinancials)
                {
                    FinancialProc_Result newItem = new FinancialProc_Result();
                    IEnumerable<FinancialProc_Result> x = financials.Where(c => c.item_description == item.item_description);

                    newItem.TOTALCOST = x.Sum(c => c.TOTALCOST);
                    newItem.Orders = x.Sum(c => c.Orders);
                    newItem.INSURANCE = item.INSURANCE;
                    newItem.SCHEME = item.SCHEME;
                    newItem.item_description = item.item_description;
                    newItem.VISITTYPE = item.VISITTYPE;
                    newItem.MARGIN = x.Sum(c => c.TOTALSELLINGPRICE) - x.Sum(c => c.TOTALCOST);
                    newItem.percentage_margins = newItem.MARGIN != 0 && newItem.TOTALCOST != 0 ? $"{newItem.MARGIN / newItem.TOTALCOST * 100:#,###0}" : $"{0:#,###0}";
                    newItem.TOTALSELLINGPRICE = x.Sum(c => c.TOTALSELLINGPRICE);
                    newItem.TOTALRETAILPRICE = x.Sum(c => c.TOTALRETAILPRICE);
                    newItem.SAVINGS = x.Sum(c => c.SAVINGS);
                    newItem.percentage_savings = newItem.SAVINGS != 0 && newItem.TOTALRETAILPRICE != 0

WOOPPlusCloud2/Views/Financial/CashReceiptsView.cshtml
@model IEnumerable<WOOPPlusCloud2.Models.CashReceipts_Result>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Cash Receipts (@ViewBag.fromDate to @ViewBag.toDate)</h3>

    </div>
    <!-- /.card-header -->
    <div class="card-body">

        @using (Html.BeginForm("CashReceiptsView", "Financial", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="">
                    <div class="col-xs-2">
                        <div class="controls">

                            <p>From:</p> @Html.TextBox("fromDate", null, new { @class = "form-control", @required = "required", @type = "date" })

                        </div>
                    </div>
                </div>

                <div class="">
                    <div class="col-xs-2">
                        <div class="controls">
                            <p>Payment Method:</p>  <select class="form-control" id="paymentMethodDropDown" name="paymentMethodDropDown">
                            </select>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="col-xs-2">
                        <div class="controls">
                            <p>Staff:</p>  <select class="form-control" id="staffDropDown" name="staffDropDown">
                            </select>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="">
                    <div class="col-xs-2">
                        <div class="controls">

                            <p>To:</p>@Html.TextBox("toDate", null, new { @class = "form-control", @required = "required", @type = "date" })


                        </div>
                    </div>
                </div>

                <div class="">
                    <div class="col-xs-2">
                        <div class="controls">
                            <p>Branch:</p>  <select class="form-control" id="branchDropDown" name="branchDropDown">
                            </select>
                        </div>
                    </div>
                </div>

                <br />

                @Html.Partial("_SearchBtn") <br /> <br />
            </div>

        }
    

    <div class="table-responsive">

            <p><b>Total: @ViewBag.Total</b></p>
            <p><b>Cash: @ViewBag.Cash</b> </p>
            <p><b>M-Pesa: @ViewBag.MPesa</b></p>
            <p><b>Cheque: @ViewBag.Cheque</b></p>
            <p><b>PDQ: @ViewBag.PDQ</b></p>
            <p><b>Bank: @ViewBag.Bank</b></p>
            <p><b>Cancelled: @ViewBag.Cancelled</b></p>

        
        <table id="tableData" class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceiptNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IssuedTo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMethod1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMethod2)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount2)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceiptAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Staff)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Center)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Cancelled)
                    </th>*@

                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReceiptNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateCreated)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IssuedTo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PaymentMethod1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PaymentMethod2)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount2)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReceiptAmount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Staff)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Center)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Cancelled)
                        </td>*@

                    </tr>
                }
            </tbody>

            <tfoot>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceiptNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IssuedTo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMethod1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentMethod2)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount2)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceiptAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Staff)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Center)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Cancelled)
                    </th>*@

                </tr>
            </tfoot>

        </table>
        <br />
        <button type="submit" id="btnExport" class="btn btn-microsoft"><span class="fa fa-angle-down"></span> Export to Excel</button>
    </div>
    </div>
</div>
@section Scripts
{

    <script type="text/javascript">
        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }
        $(function () {
            $("#tableData").DataTable({
        "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]]
            });

        });
        //Staff drop down

        $(function () {

                AjaxCall('@Url.Action("getStaff", "Financial")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#staffDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Staff</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].Staff + '">' + response[i].Staff + '</option>';
                        }
                        $('#staffDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });

          //Export Stuff
        var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "CashReceipts" });
        var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
        $("#btnExport").click(function () {
            saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'CashReceipts.xlsx');
        });
          //load branch dropdown
         $(document).ready(function () {

                AjaxCall('@Url.Action("getFacilities", "Centers")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#branchDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Select Branch</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].facility_desc + '">' + response[i].facility_desc + '</option>';
                        }
                        $('#branchDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
         });
         //load payment method dropdown
         $(document).ready(function () {

                AjaxCall('@Url.Action("getPaymentMethods", "Financial")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#paymentMethodDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Mode of Payment</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].payment_method_description + '">' + response[i].payment_method_description + '</option>';
                        }
                        $('#paymentMethodDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });
    </script>


}

WOOPPlusCloud2/Views/Financial/DepartmentRevenue.cshtml
@model IEnumerable<WOOPPlusCloud2.Models.FinancialProc_Result>

@if (Request.IsAuthenticated)
{
    ViewBag.Title = "Departmental Revenue";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departmental Revenue Report (@ViewBag.fromDate to @ViewBag.toDate)</h3>

    </div>
    @using (Html.BeginForm("DepartmentRevenue", "Financial", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>From:</p> @Html.TextBox("fromDate", null, new { @class = "form-control", @required = "required", @type = "date" })

                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Department:</p>  <select class="form-control" id="departmentDropDown" name="departmentDropDown">
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>To:</p>@Html.TextBox("toDate", null, new { @class = "form-control", @required = "required", @type = "date" })


                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Branch:</p>  <select class="form-control" id="branchDropDown" name="branchDropDown">
                        </select>
                    </div>
                </div>
            </div>
            <br /><br />
            @Html.Partial("_SearchBtn") <br /> <br />
        </div>




    }
    <div class="table-responsive">


        <table id="tableData" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Total Costs: @ViewBag.Cost
                    </th>
                    <th>
                        Total Revenue: @ViewBag.Selling
                    </th>
                    <th>
                        Total Margin: @ViewBag.Margin
                    </th>
                </tr>
            </thead>
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Orders)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.item_description)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.TOTALCOST)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TOTALSELLINGPRICE)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TOTALRETAILPRICE)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MARGIN)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.percentage_margins)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SAVINGS)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.percentage_savings)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CENTER)
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Orders)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.item_description)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.TOTALCOST)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TOTALSELLINGPRICE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TOTALRETAILPRICE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MARGIN)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.percentage_margins)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SAVINGS)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.percentage_savings)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.CENTER)
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Orders)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.item_description)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.TOTALCOST)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TOTALSELLINGPRICE)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TOTALRETAILPRICE)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MARGIN)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.percentage_margins)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SAVINGS)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.percentage_savings)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CENTER)
                    </th>

                </tr>
            </tfoot>

        </table>
        <br />

        <button type="submit" id="btnExport" class="btn btn-microsoft"><span class="fa fa-angle-down"></span> Export to Excel</button>

    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
                  //get department dropdown
        $(function () {

        AjaxCall('@Url.Action("getDepartments","Financial")', null).done(function (response) {
            if (response.length > 0) {
                $('#departmentDropDown').html('');
                var options = '';

                options += '<option value="" disabled selected>Select Department</option>';
                for (var i = 0; i < response.length; i++) {
                    options += '<option value="' + response[i].item_description + '">' +  response[i].item_description + '</option>';
                }
                $('#departmentDropDown').append(options);

            }
        }).fail(function (error) {
            alert(error.StatusText);
        });
        });

    function AjaxCall(url, data, type) {
        return $.ajax({
            url: url,
            type: type ? type : 'GET',
            data: data,
            contentType: 'application/json'
        });
        }
        //Generate data table
     $(function () {
    $("#tableData").DataTable({
        "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]]
    });
     });


        //Export Stuff
        var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "DepartmentalRevenue" });
        var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
        $("#btnExport").click(function () {
            saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'DepartmentalRevenue.xlsx');
        });
         //load branch dropdown
         $(document).ready(function () {

                AjaxCall('@Url.Action("getFacilities", "Centers")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#branchDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Select Branch</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].facility_desc + '">' + response[i].facility_desc + '</option>';
                        }
                        $('#branchDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
         });
    </script>
}