WOOPPlusCloud2/Controllers/ManageUsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WOOPPlusCloud2.Models;
using WOOPPlusCloud2.ActionFilters;
using System.Net;
using System.Web;
using System.Data.Entity;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;
using System;

namespace WOOPPlusCloud2.Controllers
{
    /// <summary>
    ///     Manage users, assign roles, approve and toggle active property.
    ///     Accessible to admin and manager
    /// </summary>
    [Authorize(Roles = "Admin")]
    [WhitespaceFilter]
    [CompressFilter]
    [ETag]
    public class ManageUsersController : Controller
    {
        //private readonly ProcedureModels _entities = new ProcedureModels();
        // private ApplicationUserManager _userManager;
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: ManageUsers
        public async Task<ActionResult> Index()
        {
            using (ApplicationDbContext _entities = new ApplicationDbContext()) 
            {
                List<ApplicationUser> users = await  _entities.Users.ToListAsync().ConfigureAwait(false);
                return View(users);
            }
                
        }

        /*// GET: ManageUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }
        */

        // GET: ManageUsers/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: ManageUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create(ApplicationUser model)
        //{
        //    using (ApplicationDbContext db = new ApplicationDbContext()) 
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            ApplicationUser user = new ApplicationUser { UserName = model.Email, Email = model.Email, PasswordHash = model.PasswordHash,/*Password = model.Password, */PhoneNumber = model.PhoneNumber /*user_roles = model.user_roles*/};

        //            IdentityResult result = await UserManager.CreateAsync(user, model.PasswordHash);

        //            if (result.Succeeded)
        //            {
        //                await this.UserManager.AddToRoleAsync(user.Id, model.user_roles);
        //                bool isActive = model.Is_Active;
        //                bool isApproved = model.Is_Approved;
        //                ProcedureModels _entities = new ProcedureModels();
        //                _entities.UpdateUsers(isActive, isApproved, user.Id);
        //                //Sign In the User by Default
        //                //await SignInManager.SignInAsync(user, false, false);


        //                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
        //                // Send an email with this link
        //                // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
        //                // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
        //                // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");
        //                //return the user to the home page after sign up
        //                //return RedirectToAction("Index", "Home");
        //                return RedirectToAction("Index");

        //            }



        //        }

        //        return View();
        //    }

        //}

        // GET: ManageUsers/Edit/5
        
        public ActionResult Edit(string id)
        {
           
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ApplicationUser applicationUser = db.Users.Find(id);
                if (applicationUser == null)
                {
                    return HttpNotFound();
                }
                ManageUsersViewModel manageUsersViewModel = new ManageUsersViewModel();
                manageUsersViewModel.Id = id;
                manageUsersViewModel.UserName = applicationUser.UserName;
                //manageUsersViewModel.s = applicationUser.staff_full_names;
                manageUsersViewModel.Is_Active = applicationUser.Is_Active;
                manageUsersViewModel.Is_Approved = applicationUser.Is_Approved;
                //string adminUserRole = ConfigurationManager.AppSettings["adminUserRole"];
                ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name", applicationUser.user_roles);
                return View(manageUsersViewModel);
            
               
        }

        // POST: ManageUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ManageUsersViewModel applicationUser)
        {
            
            
                if (String.IsNullOrEmpty(applicationUser.user_roles))
                {
                    ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");
                    ModelState.AddModelError("user_roles", "Please select a user role.");
                    return View(applicationUser);
                }

               if (ModelState.IsValid)
                {
                    ApplicationUser applicationUserToEdit = db.Users.Find(applicationUser.Id);
                    applicationUserToEdit.Is_Approved = applicationUser.Is_Approved;
                    applicationUserToEdit.Is_Active = applicationUser.Is_Active;
                    db.Entry(applicationUserToEdit).State = EntityState.Modified;
                    db.SaveChanges();
                    ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                IList<string> roles = await userManager.GetRolesAsync(applicationUser.Id).ConfigureAwait(false);
                    await userManager.RemoveFromRolesAsync(applicationUser.Id, roles.ToArray()).ConfigureAwait(false);
                    await userManager.AddToRoleAsync(applicationUser.Id, applicationUser.user_roles).ConfigureAwait(false);
                    return RedirectToAction("Index");
                }
                ViewBag.Roles = new SelectList(db.Roles.ToList(), "Name", "Name");
                return View(applicationUser);
            
               
           
        }

        // GET: ManageUsers/Delete/5
        public ActionResult Delete(string id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
            
                
        }

        //POST: ManageUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
           
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
       
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WOOPPlusCloud2/Views/ManageUsers/Create.cshtml
@model WOOPPlusCloud2.Models.ApplicationUser


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Is_Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Is_Active)
                    @Html.ValidationMessageFor(model => model.Is_Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Is_Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Is_Approved)
                    @Html.ValidationMessageFor(model => model.Is_Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WOOPPlusCloud2/Views/ManageUsers/Delete.cshtml
@model WOOPPlusCloud2.Models.ApplicationUser

<h3>Are you sure you want to delete this User?</h3>
<div>
    <h4>User Details</h4>
    <hr />
    <dl class="dl-horizontal">
     
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_roles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_roles)
        </dd>


    </dl>

    @using (Html.BeginForm("Delete", "ManageUsers", FormMethod.Post, new { role = "form" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WOOPPlusCloud2/Views/ManageUsers/Details.cshtml
@model WOOPPlusCloud.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ApplicationUser</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.staff_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_other_names)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_other_names)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_category_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_category_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.center_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.center_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.National_id_NO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.National_id_NO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_post_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_post_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_post_address_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_post_address_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_town_city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_town_city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.staff_pin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.staff_pin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_approved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_approved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

WOOPPlusCloud2/Views/ManageUsers/Edit.cshtml
@model WOOPPlusCloud2.Models.ManageUsersViewModel


@using (Html.BeginForm("Edit", "ManageUsers", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manage User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("User Role", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_roles", (SelectList)ViewBag.Roles, "-Select Role-")
                @Html.ValidationMessageFor(model => model.user_roles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Is_Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Is_Active)
                    @Html.ValidationMessageFor(model => model.Is_Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Is_Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Is_Approved)
                    @Html.ValidationMessageFor(model => model.Is_Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WOOPPlusCloud2/Views/ManageUsers/Index.cshtml
@model IEnumerable<WOOPPlusCloud2.Models.ApplicationUser>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Manage Users </h3>

    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="table-responsive">


            <table id="tableData" class="table table-bordered table-striped">
                <thead>
                    @*<p>
                        @Html.ActionLink("Create New", "Create")
                    </p>*@

                    <tr>
                        @*<th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.EmailConfirmed)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.LockoutEnabled)
                        </th>*@

                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.user_roles)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Is_Active)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Is_Approved)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmailConfirmed)
                            </td>


                            <td>
                                @Html.DisplayFor(modelItem => item.LockoutEnabled)
                            </td>*@

                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.user_roles)
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.Is_Active)</td>
                            <td>@Html.DisplayFor(modelItem => item.Is_Approved)</td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                               
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        @*<th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </th>*@

                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.user_roles)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Is_Active)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Is_Approved)
                        </th>
                        <th></th>
                        
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@section scripts
    {
    <script type="text/javascript">
        $(function () {
            $("#tableData").DataTable();

        });

        //Export Stuff
        var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "Users" });
        var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
        $("#btnExport").click(function () {
            saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'Users.xlsx');
        });
    
    </script>
    }
    