WOOPPlusCloud2/Controllers/GoodsPurchasedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WOOPPlusCloud2.ActionFilters;
using WOOPPlusCloud2.Models;

namespace WOOPPlusCloud2.Controllers
{
    [Authorize]
    
    [OutputCache(Duration = 480, VaryByParam = "none")]
    [WhitespaceFilter]
    [CompressFilter]
    [ETag]
    public class GoodsPurchasedController : Controller
    {
        // GET: GoodsPurchased
        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        public ActionResult GoodsPurchasedView(FormCollection fc)
        {
            using (ProcedureModels _entities = new ProcedureModels()) 
            {
                if (Request.HttpMethod.ToLower() == "post")
                {
                    System.Web.Helpers.AntiForgery.Validate();
                }
                DateTime fromDate;
                DateTime toDate;
                DateTime today = DateTime.Now;
                if (String.IsNullOrEmpty(fc["fromDate"]) && String.IsNullOrEmpty(fc["toDate"]))
                {
                    toDate = DateTime.Now;
                    fromDate = new DateTime(today.Year, today.Month, 1);
                }
                else
                {
                    fromDate = DateTime.Parse(fc["fromDate"]).Date;
                    
                    toDate = DateTime.Parse(fc["toDate"]).Date;
                    
                }
                ViewBag.fromDate = fromDate.ToString("dd-MM-yyyy");
                ViewBag.toDate = toDate.ToString("dd-MM-yyyy");
                List<GoodsPurchased_Result> goodsPurchased = _entities.GoodsPurchased(fromDate, toDate).ToList();
                if (!String.IsNullOrEmpty(fc["supplierDropDown"]))
                {
                    goodsPurchased = goodsPurchased.Where(c => c.supplier_name == fc["supplierDropDown"]).ToList();
                }
                IEnumerable<GoodsPurchased_Result> data = goodsPurchased.AsEnumerable();


                /*Summary of Totals and Discounts*/
                ViewBag.Total = $"{data.Sum(x => x.Total):#,###0}";
                ViewBag.Discount = $"{data.Average(x => x.discount):#,###0}";
                
                List<GoodsPurchased_Result> list = new List<GoodsPurchased_Result>();
                foreach (GoodsPurchased_Result item in goodsPurchased) 
                {
                    GoodsPurchased_Result purchasedItem = new GoodsPurchased_Result
                    {
                        trans_date = item.trans_date,
                        invoice_no = item.invoice_no,
                        product_code = item.product_code,
                        DRUG = item.DRUG,
                        Quantity = item.Quantity,
                        batch_no = item.batch_no,
                        expiry_date = item.expiry_date,
                        supplier_name = item.supplier_name,
                        discount = item.discount,
                        vatvalue = item.vatvalue,
                        Total = item.Total,
                        vat_ex_amount = item.vat_ex_amount,
                        UnitIncDisc = (item.Total - item.discount) / Convert.ToDecimal(item.Quantity),
                        UnitexDisc = item.Total / Convert.ToDecimal(item.Quantity)
                    };
                    list.Add(purchasedItem);

                }
                return View(list);
            }
                
        }
        public JsonResult getSupplier()
        {
            using (ProcedureModels _entities = new ProcedureModels())
            {
                DateTime toDate = DateTime.Now;
                DateTime fromDate = toDate.AddYears(-1);
                List<GoodsPurchased_Result> supplier = _entities.GoodsPurchased(fromDate, toDate).GroupBy(c => c.supplier_name).Select(c => c.First()).OrderBy(c => c.supplier_name).ToList();
                List<GoodsPurchased_Result> list = new List<GoodsPurchased_Result>();
                foreach (GoodsPurchased_Result item in supplier)
                {
                    GoodsPurchased_Result supplierItem = new GoodsPurchased_Result
                    {
                        supplier_name = item.supplier_name
                    };
                    list.Add(supplierItem);
                }

                return Json(list, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

WOOPPlusCloud2/Views/GoodsPurchased/GoodsPurchasedView.cshtml
@model  IEnumerable<WOOPPlusCloud2.Models.GoodsPurchased_Result> 
<div class="card">
<div class="card-header">
    <h3 class="card-title">Goods Purchased Report (@ViewBag.fromDate to @ViewBag.toDate)</h3>
</div>
<!-- /.card-header -->
<div class="card-body">
    @using (Html.BeginForm("GoodsPurchasedView", "GoodsPurchased", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_DateSearch")

        <div class="">
            <div class="col-xs-2">
                <div class="controls">
                    <p>Supplier:</p>  <select class="form-control" id="supplierDropDown" name="supplierDropDown">
                    </select>
                </div>
            </div>
        </div>
        <br /><br />
        
        @Html.Partial("_SearchBtn")<br /> <br />

    }


<div class="table-responsive">


    <table id="tableData" class="table table-bordered table-striped">
        <thead>


            <tr>
                <th>
                    Total Purchased: @ViewBag.Total
                </th>
                <th>
                    Average Discount: @ViewBag.Discount
                </th>
                <th>
                    Margin: @ViewBag.Margin
                </th>
            </tr>
        </thead>
        <thead>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.trans_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.invoice_no)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.product_code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DRUG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitexDisc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.discount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitIncDisc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.vatvalue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.vat_ex_amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.batch_no)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.expiry_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.supplier_name)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.trans_date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.invoice_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.product_code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DRUG)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitexDisc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.discount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitIncDisc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.vatvalue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.vat_ex_amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.batch_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.expiry_date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.supplier_name)
                    </td>

                </tr>
            }
        </tbody>


        <tfoot>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.trans_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.invoice_no)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.product_code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DRUG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitexDisc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.discount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitIncDisc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.vatvalue)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.vat_ex_amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.batch_no)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.expiry_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.supplier_name)
                </th>

            </tr>
        </tfoot>

    </table>
    <br />
    <button type="submit" id="btnExport" class="btn btn-microsoft"><span class="fa fa-angle-down"></span> Export to Excel</button>

</div>
</div>
    </div>
@section Scripts
{
    <script type="text/javascript">

         $(function () {

            AjaxCall('@Url.Action("getSupplier","GoodsPurchased")', null).done(function (response) {
                if (response.length > 0) {
                    $('#supplierDropDown').html('');
                    var options = '';

                    options += '<option value="" disabled selected>Select Supplier</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].supplier_name + '">' +  response[i].supplier_name + '</option>';
                    }
                    $('#supplierDropDown').append(options);

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });



        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }
            $(function () {
    $("#tableData").DataTable({
        "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]]
    });

                 });
         //Export Stuff
    var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "GoodsPurchased" });
    var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
    function s2ab(s) {
        var buf = new ArrayBuffer(s.length);
        var view = new Uint8Array(buf);
        for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
        return buf;
    }
    $("#btnExport").click(function () {
        saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'GoodsPurchased.xlsx');
    });

    </script>
}