WOOPPlusCloud2/ViewModels/AgingViewModel.cs
using PagedList;
using WOOPPlusCloud2.Models;

namespace WOOPPlusCloud2.ViewModels
{
    public class AgingViewModel
    {
        public IPagedList<AgingProc_Result> AgingProcResults { get; set; }
    }
}

WOOPPlusCloud2/Controllers/AgingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WOOPPlusCloud2.Models;
using WOOPPlusCloud2.ActionFilters;
using System.Threading.Tasks;

namespace WOOPPlusCloud2.Controllers
{
    [Authorize]
    //[OutputCache(Duration = 480, VaryByParam = "none")]

    public class AgingController : Controller
    {
        
        private delegate List<AgingProc_Result> AgingSPDelegate();

        // GET: Aging

        private List<AgingProc_Result> Aging()
        {
            using (ProcedureModels _entities = new ProcedureModels()) 
            {
                List<AgingProc_Result> list = new List<AgingProc_Result>();
                //Exclude hub and whole sale 
                List<AgingProc_Result> aging = _entities.AgingProc().Where(c => c.payment_account_desc != "WHOLE SALE").Where(c => c.payment_account_desc != "HUB").ToList();

                List<AgingProc_Result> groupedAging = aging.GroupBy(c => c.payment_account_id).Select(c => c.First()).ToList();
                decimal? totalCharged = aging.Sum(c => c.TOTALCHARGE);
                decimal? totalPaid = aging.Sum(c => c.PAIDAMOUNT);
                decimal? totalBalance = totalCharged - totalPaid;

                ViewBag.RunningBalance = $"{totalBalance:#,###0}";
                ViewBag.TotalCharge = $"{totalCharged:#,###0}";
                ViewBag.TotalPaid = $"{totalPaid:#,###0}";

                foreach (AgingProc_Result item in groupedAging)
                {
                    AgingProc_Result newItem = new AgingProc_Result
                    {
                        payment_account_desc = item.payment_account_desc
                    };
                    IEnumerable<AgingProc_Result> group = aging.Where(c => c.payment_account_id == item.payment_account_id);
                    IEnumerable<AgingProc_Result> agingProcResults = group.ToList();
                    //total charged
                    newItem.TOTALCHARGE = agingProcResults.Sum(c => c.TOTALCHARGE);
                    //paid amount
                    newItem.PAIDAMOUNT = agingProcResults.Sum(c => c.PAIDAMOUNT);
                    //unallocated amount
                    newItem.unallocated_amount = item.unallocated_amount;
                    //running balance
                    newItem.running_balance = newItem.TOTALCHARGE - newItem.PAIDAMOUNT;

                    //aging stuff 
                    IEnumerable<AgingProc_Result> overOneFifty = agingProcResults.Where(c =>
                        DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-150));
                    newItem.summary_over_one_fifty = overOneFifty.Sum(c => c.TOTALCHARGE) - overOneFifty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> over = agingProcResults.Where(c =>
                        DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-120));
                    newItem.summary = over.Sum(c => c.TOTALCHARGE) - over.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overNinety = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-90) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-120));
                    newItem.summary_ninety = overNinety.Sum(c => c.TOTALCHARGE) - overNinety.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overSixty = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-60) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-90));
                    newItem.summary_sixty = overSixty.Sum(c => c.TOTALCHARGE) - overSixty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overThirty = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-30) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-60));
                    newItem.summary_thirty = overThirty.Sum(c => c.TOTALCHARGE) - overThirty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> current = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-30));
                    newItem.summary_current = current.Sum(c => c.TOTALCHARGE) - current.Sum(c => c.PAIDAMOUNT);


                    list.Add(newItem);
                }
                return list;
            }
                
        }

        public Task<List<AgingProc_Result>> AgingAsync()
        {
            AgingSPDelegate caller = new AgingSPDelegate(Aging);
            return Task.Factory.FromAsync(caller.BeginInvoke, caller.EndInvoke, null);
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Get)]
        [Authorize]
        [OutputCache(Duration = 480, VaryByParam = "none")]
        [WhitespaceFilter]
        [CompressFilter]
        [ETag]
        public async Task<ActionResult> AgingReportView(FormCollection fc)
        {
            if (Request.HttpMethod.ToLower() == "post")
            {
                System.Web.Helpers.AntiForgery.Validate();
            }
            DateTime fromDate;
            DateTime toDate;
            List<AgingProc_Result> list = await AgingAsync().ConfigureAwait(false);
            if (!String.IsNullOrEmpty(fc["fromDate"]) && !String.IsNullOrEmpty(fc["toDate"]))
            {
                fromDate = DateTime.Parse(fc["fromDate"]).Date;
                toDate = DateTime.Parse(fc["toDate"]).Date;
                List<AgingProc_Result> groupedAging = list.GroupBy(c => c.payment_account_id).Select(c => c.First())
                .Where(c => c.invoice_closed_date >= fromDate && c.invoice_closed_date <= toDate).ToList();
                decimal? totalCharged = list.Sum(c => c.TOTALCHARGE);
                decimal? totalPaid = list.Sum(c => c.PAIDAMOUNT);
                decimal? totalBalance = totalCharged - totalPaid;

                ViewBag.RunningBalance = $"{totalBalance:#,###0}";
                ViewBag.TotalCharge = $"{totalCharged:#,###0}";
                ViewBag.TotalPaid = $"{totalPaid:#,###0}";

                foreach (AgingProc_Result item in groupedAging)
                {
                    AgingProc_Result newItem = new AgingProc_Result
                    {
                        payment_account_desc = item.payment_account_desc
                    };
                    IEnumerable<AgingProc_Result> group = list.Where(c => c.payment_account_id == item.payment_account_id);
                    IEnumerable<AgingProc_Result> agingProcResults = group.ToList();
                    newItem.TOTALCHARGE = agingProcResults.Sum(c => c.TOTALCHARGE);
                    newItem.PAIDAMOUNT = agingProcResults.Sum(c => c.PAIDAMOUNT);
                    newItem.running_balance = newItem.TOTALCHARGE - newItem.PAIDAMOUNT;
                    //unallocated amount
                    newItem.unallocated_amount = item.unallocated_amount;

                    //aging stuff 

                    IEnumerable<AgingProc_Result> overOneFifty = agingProcResults.Where(c =>
                        DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-150));
                    newItem.summary_over_one_fifty = overOneFifty.Sum(c => c.TOTALCHARGE) - overOneFifty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> over = agingProcResults.Where(c =>
                        DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-120));
                    newItem.summary = over.Sum(c => c.TOTALCHARGE) - over.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overNinety = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-90) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-120));
                    newItem.summary_ninety = overNinety.Sum(c => c.TOTALCHARGE) - overNinety.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overSixty = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-60) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-90));
                    newItem.summary_sixty = overSixty.Sum(c => c.TOTALCHARGE) - overSixty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> overThirty = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) < DateTime.Today.AddDays(-30) && DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-60));
                    newItem.summary_thirty = overThirty.Sum(c => c.TOTALCHARGE) - overThirty.Sum(c => c.PAIDAMOUNT);
                    IEnumerable<AgingProc_Result> current = agingProcResults.Where(c => DateTime.Parse(c.invoice_closed_date.ToString()) > DateTime.Today.AddDays(-30));
                    newItem.summary_current = current.Sum(c => c.TOTALCHARGE) - current.Sum(c => c.PAIDAMOUNT);
                    
                    list.Add(newItem);
                }

                return View(list);

            }
            else 
            {
                return View(list);
            } 
           
        }

    }
}

WOOPPlusCloud2/Views/Aging/AgingReportView.cshtml
@model  IEnumerable<WOOPPlusCloud2.Models.AgingProc_Result>

@if (Request.IsAuthenticated)
{
    ViewBag.Title = "AgingReportView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Aging Report</h3>

    </div>
    <!-- /.card-header -->
    <div class="card-body">

        <!-- /.box-header -->
        @using (Html.BeginForm("AgingReportView", "Aging", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
        <div class="row">
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>From:</p> @Html.TextBox("fromDate", null, new { @class = "form-control", @required = "required", @type = "date" })

                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Invoice Type:</p>  <select class="form-control" id="schemeDropDown" name="schemeDropDown">
                            <option value="" disabled selected>All</option>
                            <option value="insurance">By Insurance</option>
                            <option value="scheme">By Scheme</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">


            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>To:</p>@Html.TextBox("toDate", null, new { @class = "form-control", @required = "required", @type = "date" })


                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Branch:</p>  <select class="form-control" id="branchDropDown" name="branchDropDown">
                        </select>
                    </div>
                </div>
            </div>
            <br />
            @Html.Partial("_SearchBtn")<br /> <br />
        </div>

        }
        
        <div class="table-responsive">


            <table id="tableData" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Total Charged: @ViewBag.TotalCharge
                        </th>
                        <th>
                            Total Paid:  @ViewBag.TotalPaid
                        </th>
                        <th>
                            Running Balance: @ViewBag.RunningBalance
                        </th>
                    </tr>
                </thead>

                <thead>
                    <tr>
                        <th>
                            Insurance
                        </th>
                        <th>
                            Current
                        </th>
                        <th>
                            30 Days
                        </th>
                        <th>
                            60 Days
                        </th>
                        <th>
                            90 Days
                        </th>
                        <th>
                            120 & Above
                        </th>
                        <th>
                            150 & Above
                        </th>

                        <th>
                            Total
                        </th>

                        <th>
                            Unallocated
                        </th>
                        <th>
                            Collection
                        </th>
                        <th>
                            Balance
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.payment_account_desc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_current)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_thirty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_sixty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_ninety)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_over_one_fifty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TOTALCHARGE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.unallocated_amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PAIDAMOUNT)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.running_balance)
                        </td>

                        <td>
                            @*@Html.DisplayFor(modelItem => item.CENTER)*@
                        </td>
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>
                            Insurance
                        </th>
                        <th>
                            Current
                        </th>
                        <th>
                            30 Days
                        </th>
                        <th>
                            60 Days
                        </th>
                        <th>
                            90 Days
                        </th>
                        <th>
                            120 & Above
                        </th>
                        <th>
                            150 & Above
                        </th>

                        <th>
                            Total
                        </th>

                        <th>
                            Unallocated
                        </th>
                        <th>
                            Collection
                        </th>
                        <th>
                            Balance
                        </th>
                    </tr>
                </tfoot>
            </table>
            <br />

            <button type="submit" id="btnExport" class="btn btn-microsoft"><span class="fa fa-angle-down"></span> Export to Excel</button>

        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
          $(function () {

            AjaxCall('@Url.Action("getInsurance","DiagnosisReport")', null).done(function (response) {
                if (response.length > 0) {
                    $('#insuranceDropDown').html('');
                    var options = '';

                    options += '<option value="" disabled selected>Select Insurance</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].code + '">' +  response[i].payment_account_desc + '</option>';
                    }
                    $('#insuranceDropDown').append(options);

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });



        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                async: true,
                contentType: 'application/json'
            });
                }

         $(function () {
            $("#tableData").DataTable({
        "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]]
    });
        });
        //Export Stuff
        var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "Aging" });
        var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
        $("#btnExport").click(function () {
            saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'Aging.xlsx');
        });
             //load branch dropdown
         $(document).ready(function () {

                AjaxCall('@Url.Action("getFacilities", "Centers")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#branchDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Select Branch</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].facility_desc + '">' + response[i].facility_desc + '</option>';
                        }
                        $('#branchDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });
    </script>
    }

WOOPPlusCloud2/Views/Aging/AgingReportViewUngrouped.cshtml
@model  IEnumerable<WOOPPlusCloud2.Models.AgingProc_Result>

@if (Request.IsAuthenticated)
{
    ViewBag.Title = "AgingReportView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Aging Report</h3>

    </div>
    <!-- /.card-header -->
    <div class="card-body">

        <!-- /.box-header -->
        @using (Html.BeginForm("AgingReportView", "Aging", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
        <div class="row">
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>From:</p> @Html.TextBox("fromDate", null, new { @class = "form-control", @required = "required", @type = "date" })

                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Invoice Type:</p>  <select class="form-control" id="schemeDropDown" name="schemeDropDown">
                            <option value="" disabled selected>All</option>
                            <option value="insurance">By Insurance</option>
                            <option value="scheme">By Scheme</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">


            <div class="">
                <div class="col-xs-2">
                    <div class="controls">

                        <p>To:</p>@Html.TextBox("toDate", null, new { @class = "form-control", @required = "required", @type = "date" })


                    </div>
                </div>
            </div>
            <div class="">
                <div class="col-xs-2">
                    <div class="controls">
                        <p>Branch:</p>  <select class="form-control" id="branchDropDown" name="branchDropDown">
                        </select>
                    </div>
                </div>
            </div>
            <br />
            @Html.Partial("_SearchBtn")<br /> <br />
        </div>

        }
        
        <div class="table-responsive">


            <table id="tableData" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            Total Charged: @ViewBag.TotalCharge
                        </th>
                        <th>
                            Total Paid:  @ViewBag.TotalPaid
                        </th>
                        <th>
                            Running Balance: @ViewBag.RunningBalance
                        </th>
                    </tr>
                </thead>

                <thead>
                    <tr>
                        <th>
                            Insurance
                        </th>
                        <th>
                            Scheme
                        </th>
                        <th>
                            Current
                        </th>
                        <th>
                            30 Days
                        </th>
                        <th>
                            60 Days
                        </th>
                        <th>
                            90 Days
                        </th>
                        <th>
                            120 & Above
                        </th>
                        <th>
                            150 & Above
                        </th>

                        <th>
                            Total
                        </th>

                        <th>
                            Unallocated
                        </th>
                        <th>
                            Collection
                        </th>
                        <th>
                            Balance
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.payment_account_desc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.patient_payment_account_type_desc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_current)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_thirty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_sixty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_ninety)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.summary_over_one_fifty)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TOTALCHARGE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.unallocated_amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PAIDAMOUNT)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.running_balance)
                        </td>

                        <td>
                            @*@Html.DisplayFor(modelItem => item.CENTER)*@
                        </td>
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>
                            Insurance Company
                        </th>
                        <th>
                            Current
                        </th>
                        <th>
                            30 Days
                        </th>
                        <th>
                            60 Days
                        </th>
                        <th>
                            90 Days
                        </th>
                        <th>
                            120 & Above
                        </th>
                        <th>
                            150 & Above
                        </th>

                        <th>
                            Total
                        </th>

                        <th>
                            Unallocated
                        </th>
                        <th>
                            Collection
                        </th>
                        <th>
                            Balance
                        </th>
                    </tr>
                </tfoot>
            </table>
            <br />

            <button type="submit" id="btnExport" class="btn btn-microsoft"><span class="fa fa-angle-down"></span> Export to Excel</button>

        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
          $(function () {

            AjaxCall('@Url.Action("getInsurance","DiagnosisReport")', null).done(function (response) {
                if (response.length > 0) {
                    $('#insuranceDropDown').html('');
                    var options = '';

                    options += '<option value="" disabled selected>Select Insurance</option>';
                    for (var i = 0; i < response.length; i++) {
                        options += '<option value="' + response[i].code + '">' +  response[i].payment_account_desc + '</option>';
                    }
                    $('#insuranceDropDown').append(options);

                }
            }).fail(function (error) {
                alert(error.StatusText);
            });



        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                async: true,
                contentType: 'application/json'
            });
                }

         $(function () {
            $("#tableData").DataTable({
        "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]]
    });
        });
        //Export Stuff
        var wb = XLSX.utils.table_to_book(document.getElementById('tableData'), { sheet: "Aging" });
        var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
        function s2ab(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }
        $("#btnExport").click(function () {
            saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'Aging.xlsx');
        });
             //load branch dropdown
         $(document).ready(function () {

                AjaxCall('@Url.Action("getFacilities", "Centers")', null).done(function (response) {
                    if (response.length > 0) {
                        $('#branchDropDown').html('');
                        var options = '';
                        options += '<option value="" disabled selected>Select Branch</option>'
                        for (var i = 0; i < response.length; i++) {
                            options += '<option value="' + response[i].facility_desc + '">' + response[i].facility_desc + '</option>';
                        }
                        $('#branchDropDown').append(options);

                    }
                }).fail(function (error) {
                    alert(error.StatusText);
                });
            });
    </script>
    }